### PR TITLE
Fix code blocks

### PR DESCRIPTION
**Pull request by fintelia**
*Description of changes:* Fix missing backticks to end some code blocks

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by fabiosky** [comment]
Hello Jonathan,

thanks for your patch.

The build is not passing due to some linter errors. See build log for details.

Could you please run the following command and fix those?
`cargo clippy --all-targets -- -D warnings`

Thanks,
Fabio

**Review by fabiosky — CHANGES_REQUESTED** [review]
Hello Jonathan,

thanks for your patch.

The build is not passing due to some linter errors. See build log for details.

Could you please run the following command and fix those?
`cargo clippy --all-targets -- -D warnings`

Thanks,
Fabio

**Comment by fintelia** [comment]
There's a certain irony of having Clippy's markdown formatting lint previously not trigger due to a markdown formatting issue :laughing:

**Comment by fintelia** [comment]
Not sure what's going on with the CI coverage check failure. This PR only modifies doc comments so I don't think it should impact code coverage

**Comment by fabiosky** [comment]
HI Jonathan,
yes there is some regression on the coverage, but it's not caused by this pr.

Merging it.

Thanks!

**Pull request merged**
