### PR TITLE
Derive debug for public types

### PR DESCRIPTION
**Pull request by FlareFlo**
*Issue #:*
#80

*Description of changes:*
Deriving Debug for public types.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by FlareFlo** [comment]
Note: This is considered a breaking change and requires a version bump.

**Comment by fabiosky** [comment]
Thanks for the PR!
A new release will be available in minutes.

**Comment by fabiosky** [comment]
Here's the release:
https://github.com/aws/dcv-color-primitives/releases/tag/v0.6.1

**Comment by fabiosky** [comment]
https://crates.io/crates/dcv-color-primitives  is now pointing to 0.6.1

**Pull request merged**
